apiVersion: v1
kind: Secret
metadata:
  name: grafana-datasource-secret
  namespace: grafana-monitoring
type: Opaque
stringData:
  datasource.yaml: |-
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus:9090
        isDefault: true
        jsonData:
          timeInterval: "5s"
          httpMethod: "POST"
        secureJsonData:
          tlsSkipVerify: true
