apiVersion: v1
kind: Secret
metadata:
  name: grafana-datasource-secret
type: Opaque
stringData:
  datasource.yaml: |-
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus:9090
        isDefault: true
        jsonData:
          timeInterval: "5s"
        secureJsonData:
          basicAuthPassword: password
          basicAuthUser: user
          tlsSkipVerify: true
      - name: Random Walk
        type: grafana-random-walk
        access: proxy
        url: http://random-walk:8080
        isDefault: false
        jsonData:
          timeInterval: "5s"
        secureJsonData:
          basicAuthPassword: password
          basicAuthUser: user
          tlsSkipVerify: true