apiVersion: 1
kind: Secret
metadata:
  name: grafana-datasource-secret
type: Opaque
data:
  datasource.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus:9090
        isDefault: true
        jsonData:
          timeInterval: 5s
        secureJsonData:
          basicAuthPassword: cGFzc3dvcmQ=
          tlsSkipVerify: true
          basicAuthUser: dXNlcg==
          tlsSkipVerify: true
      - name: Random Walk
        type: grafana-random-walk
        access: proxy
        url: http://random-walk:8080
        isDefault: false
        jsonData:
          timeInterval: 5s
        secureJsonData:
          basicAuthPassword: cGFzc3dvcmQ=
          tlsSkipVerify: true
          basicAuthUser: dXNlcg==
          tlsSkipVerify: true