apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana_dashboard_config
  labels:
    grafana_dashboard: "1"
data:
  dashboards/grafana_dashboard_config: |
    {
      "dashboard": {
        "id": null,
        "uid": null,
        "title": "Sample Dashboard",
        "tags": [],
        "timezone": "browser",
        "schemaVersion": 16,
        "version": 0,
        "refresh": "5s",
        "panels": [
          {
            "type": "graph",
            "title": "Sample Graph",
            "gridPos": {
              "x": 0,
              "y": 0,
              "w": 24,
              "h": 9
            },
            "id": 1,
            "datasource": null,
            "targets": [
              {
                "target": "sample.metric",
                "refId": "A"
              }
            ],
            "lines": true,
            "linewidth": 1,
            "nullPointMode": "null"
          }
        ]
      },
      "overwrite": false
    }