apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  labels:
    grafana_datasource: "1"
data:
  random-walk-datasource.yaml: |
    apiVersion: 1
    datasources:
      - name: Random Walk Data
        type: testdata
        access: proxy
        isDefault: true