apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-dashboard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana-dashboard
  template:
    metadata:
      labels:
        app: grafana-dashboard
    spec:
      containers:
      - name: grafana
        image: grafana/grafana:latest
        volumeMounts:
        - name: grafana-dashboard-config
          mountPath: /var/lib/grafana/dashboards
          readOnly: true
      volumes:
      - name: grafana-dashboard-config
        configMap:
          name: grafana-dashboard