admin:
  ## @param admin.user Grafana admin username
  ##
  user: "admin"
  ## @param admin.password Admin password. If a password is not provided a random password will be generated
  ##
  password: "your-password"

## Grafana Image Renderer configuration for Grafana
##
imageRenderer:
  ## @param imageRenderer.enabled Enable using a remote rendering service to render PNG images
  ##
  enabled: true
  ## @param imageRenderer.serverURL URL of the remote rendering service
  ##
  serverURL: "http://grafana-imagerenderer.grafana-monitoring.svc.cluster.local:8081/render"
  ## @param imageRenderer.callbackURL URL of the callback service
  ##
  callbackURL: "http://grafana.grafana-monitoring.svc.cluster.local:3000/"

## @section Grafana Deployment parameters
grafana:
  ## @param grafana.replicaCount Number of Grafana nodes
  ##
  replicaCount: 1
  persistence:
    enabled: true
    size: 100Mi
  service:
    type: NodePort
    port: 3000
    nodePort: 30000
  plugins:
    - grafana-image-renderer
  initContainers:
    - name: init-chmod-data
      image: busybox
      command: ['sh', '-c', 'chmod -R 777 /var/lib/grafana']
      volumeMounts:
        - name: grafana-storage
          mountPath: /var/lib/grafana
    - name: install-ping
      image: alpine
      command: ['sh', '-c', 'apk add --no-cache iputils && sleep 1']
  extraVolumes:
    - name: grafana-storage
      emptyDir: {}

## Service parameters
##
service:
  ## @param service.type Kubernetes Service type
  ##
  type: ClusterIP
  ## @param service.clusterIP Grafana service Cluster IP
  ## e.g.:
  ## clusterIP: None
  ##
  # clusterIP: ""
  ## @param service.ports.grafana Grafana service port
  ##
  ports:
    grafana: 3000