apiVersion: 1
kind: Secret
metadata:
  name: grafana-datasource-secret
  namespace: grafana-monitoring
type: Opaque
stringData:
  datasource.yaml: |-
    apiVersion: 1
    datasources:
      - name: TestData
        type: testdata
