apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources1
  labels:
    grafana_datasource: "1"
data:
  datasource1.yaml: |
    apiVersion: 1

    datasources:
      - name: MetricData
        type: prometheus
        url: http://your-prometheus-server:9090
        access: proxy
        basicAuth: false